//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampoRequest
    {
        public int id_campo { get; set; }
        public int id_seccion { get; set; }
        public string nom_campo { get; set; }
        public string desc_campo { get; set; }
        public string estado_campo { get; set; }
        public string oblig_campo { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual SeccionRequest seccion { get; set; }
    }
}
