//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstFmtMayoristaRequest
    {
        public int id_formato { get; set; }
        public int id_instancia { get; set; }
        public int cantidad { get; set; }
        public decimal volumen { get; set; }
        public decimal precio_min { get; set; }
        public decimal precio_max { get; set; }
        public string observaciones { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public int id_especie { get; set; }
        public int id_unidad { get; set; }
        public int id_lugar { get; set; }
        public int id_estado { get; set; }
        public int id_presentacion { get; set; }
        public decimal peso_unidad { get; set; }
        public decimal tamanio { get; set; }
    
        public virtual EspecieRequest especie { get; set; }
        public virtual EstadoRequest estado { get; set; }
        public virtual UnidadRequest unidad { get; set; }
        public virtual LugarRequest lugar { get; set; }
        public virtual PresentacionRequest presentacion { get; set; }
        public virtual InstFormatoRequest inst_formato { get; set; }
    }
}
