//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Repositorio
{
    using MERCADOS.Entidades;
    using MERCADOS.IRepositorio;
    using System;
    using System.Collections.Generic;
    
    public partial class LugarRepositorio : BaseRepositorio<DAT_LUGAR>, ILugarRepositorio
    {
    	public LugarRepositorio(IContext context) : base(context) { }
    }
}
