//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DAT_INST_FORMATO
    {
        [Key, Column(Order = 0)]
        public int id_formato { get; set; }

        [Key, Column(Order = 1)]
        public int id_instancia { get; set; }

        public int id_mercado { get; set; }
        public string user_instancia { get; set; }
        public string estado_instancia { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }

        [ForeignKey("id_formato")]
        public virtual DAT_FORMATO DAT_FORMATO { get; set; }

        [ForeignKey("id_formato, id_instancia")]
        public virtual DAT_INST_FMT_MAYORISTA DAT_INST_FMT_MAYORISTA { get; set; }

        [ForeignKey("id_formato, id_instancia")]
        public virtual DAT_INST_FMT_MINORISTA DAT_INST_FMT_MINORISTA { get; set; }

        [ForeignKey("id_mercado")]
        public virtual DAT_MERCADO DAT_MERCADO { get; set; }
    }
}
