//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DAT_FORMATO
    {
        public DAT_FORMATO()
        {
            this.DAT_SECCION = new HashSet<DAT_SECCION>();
            this.DAT_INST_FORMATO = new HashSet<DAT_INST_FORMATO>();
        }

        [Key]
        public int id_formato { get; set; }
        public int tipo_formato { get; set; }
        public string nom_formato { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<DAT_SECCION> DAT_SECCION { get; set; }
        public virtual ICollection<DAT_INST_FORMATO> DAT_INST_FORMATO { get; set; }
    }
}
