//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DAT_UNIDAD
    {
        public DAT_UNIDAD()
        {
            this.DAT_INST_FMT_MAYORISTA = new HashSet<DAT_INST_FMT_MAYORISTA>();
            this.DAT_INST_FMT_MINORISTA = new HashSet<DAT_INST_FMT_MINORISTA>();
        }

        [Key]
        public int id_unidad { get; set; }
        public string nom_unidad { get; set; }
        public string estado_unidad { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual ICollection<DAT_INST_FMT_MAYORISTA> DAT_INST_FMT_MAYORISTA { get; set; }
        public virtual ICollection<DAT_INST_FMT_MINORISTA> DAT_INST_FMT_MINORISTA { get; set; }
    }
}
