//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DAT_SECCION
    {
        public DAT_SECCION()
        {
            this.DAT_CAMPO = new HashSet<DAT_CAMPO>();
        }

        [Key]
        public int id_seccion { get; set; }
        public int id_formato { get; set; }
        public string nom_seccion { get; set; }
        public int orden_seccion { get; set; }
        public string estado_seccion { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual ICollection<DAT_CAMPO> DAT_CAMPO { get; set; }
        public virtual DAT_FORMATO DAT_FORMATO { get; set; }
    }
}
