//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DAT_MERCADO
    {
        public DAT_MERCADO()
        {
            this.DAT_INST_FORMATO = new HashSet<DAT_INST_FORMATO>();
        }

        [Key]
        public int id_mercado { get; set; }
        public string nom_mercado { get; set; }
        public string desc_mercado { get; set; }
        public string distrito_mercado { get; set; }
        public string estado_mercado { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual ICollection<DAT_INST_FORMATO> DAT_INST_FORMATO { get; set; }
    }
}
