//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCADOS.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VW_MAESTRO_CAMPO
    {
        [Key]
        public int id_campo { get; set; }

        public string nom_seccion { get; set; }
        public string nom_formato { get; set; }
        public string nom_campo { get; set; }
        public string desc_campo { get; set; }
        public string estado { get; set; }
        public string obligatorio { get; set; }
        public string ult_usuario { get; set; }
        public System.DateTime ult_fecha { get; set; }
    }
}
